import React from 'react';
import{useMemo,useState}from"react";import{NavLink,Route,Routes,Link,useParams}from"react-router-dom";import{BookOpen,Search,BarChart3,User,Clock3,Star,ArrowRight}from"lucide-react";
const courses=[["web","Modern Web Development","Web","Intermediate","8 weeks",4.9,"https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1400&q=90"],["react","React from Zero to Production","Frontend","Intermediate","6 weeks",4.8,"https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1400&q=90"],["data","Data Science Foundations","Data","Beginner","10 weeks",4.9,"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=90"],["python","Python for Data Analysis","Data","Beginner","7 weeks",4.7,"https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1400&q=90"],["ui","UI/UX Design Essentials","Design","Beginner","5 weeks",4.8,"https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1400&q=90"],["cloud","Cloud Fundamentals","Cloud","Intermediate","6 weeks",4.6,"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1400&q=90"],["js","JavaScript Deep Dive","Frontend","Advanced","9 weeks",4.9,"https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=1400&q=90"],["sql","SQL & Database Design","Data","Intermediate","6 weeks",4.7,"https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=1400&q=90"]];
const desc="A practical course designed for students who want to build modern technical skills.";
function Header(){return <header className="header"><div className="container nav"><Link className="brand" to="/"><BookOpen size={24}/>EduFlow</Link><nav><NavLink to="/">Home</NavLink><NavLink to="/courses">Courses</NavLink><NavLink to="/dashboard">Dashboard</NavLink><NavLink to="/profile">Profile</NavLink></nav></div></header>}
function Card({c}){return <article className="card"><img src={c[6]} alt={c[1]}/><div className="body"><span className="tag">{c[2]}</span><h3>{c[1]}</h3><p>{desc}</p><div className="meta"><span><Star size={15}/>{c[5]}</span><span><Clock3 size={15}/>{c[4]}</span></div><Link className="btn secondary" to={"/courses/"+c[0]}>View course <ArrowRight size={16}/></Link></div></article>}
function Home(){return <><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">LEARN • BUILD • GROW</span><h1>Learn skills that move your career forward.</h1><p>EduFlow is a research-oriented e-learning interface used to evaluate practical web performance optimization techniques.</p><div className="actions"><Link className="btn primary" to="/courses">Explore courses</Link><Link className="btn ghost" to="/dashboard">Dashboard</Link></div></div><div className="hero-panel"><BarChart3 size={42}/><h3>Performance Research</h3><p>The same application is measured before and after controlled optimizations.</p></div></div></section><section className="container section"><div className="section-head"><div><span className="eyebrow">POPULAR</span><h2>Featured courses</h2></div><Link to="/courses">View all</Link></div><div className="grid">{courses.slice(0,4).map(c=><Card key={c[0]} c={c}/>)}</div></section></>}
function Courses(){const[q,setQ]=useState(""),[cat,setCat]=useState("All"),cats=["All",...new Set(courses.map(c=>c[2]))],filtered=useMemo(()=>courses.filter(c=>(cat==="All"||c[2]===cat)&&c[1].toLowerCase().includes(q.toLowerCase())),[q,cat]);return <main className="container section"><div className="page-head"><span className="eyebrow">COURSE LIBRARY</span><h1>Explore courses</h1><p>Search and filter the catalog.</p></div><div className="filters"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search courses..."/></div><div className="chips">{cats.map(x=><button className={cat===x?"chip active":"chip"} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></div><div className="grid">{filtered.map(c=><Card key={c[0]} c={c}/>)}</div></main>}
function Details(){const{id}=useParams(),c=courses.find(x=>x[0]===id);if(!c)return <main className="container section"><h1>Course not found</h1></main>;return <main className="container section"><div className="details"><img src={c[6]} alt={c[1]}/><div><span className="tag">{c[2]}</span><h1>{c[1]}</h1><p>{desc}</p><div className="meta large"><span><Star size={17}/>{c[5]}</span><span>{c[3]}</span><span><Clock3 size={17}/>{c[4]}</span></div><button className="btn primary">Enroll now</button></div></div></main>}
function Dashboard(){return <main className="container section"><span className="eyebrow">STUDENT AREA</span><h1>Dashboard</h1><div className="stats"><div><b>3</b><span>Active courses</span></div><div><b>68%</b><span>Average progress</span></div><div><b>12</b><span>Hours learned</span></div></div><div className="card panel"><h2>Continue learning</h2><p>React from Zero to Production — 72% complete</p><div className="progress"><i/></div></div></main>}
function Profile(){return <main className="container section"><span className="eyebrow">ACCOUNT</span><h1>Profile</h1><div className="card panel profile"><User size={42}/><div><h2>Alex Morgan</h2><p>Computer Science Student</p><p>Interested in web development and data science.</p></div></div></main>}
export default function App(){return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/courses" element={<Courses/>}/><Route path="/courses/:id" element={<Details/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/profile" element={<Profile/>}/></Routes><footer><div className="container">EduFlow Research Prototype • Web Performance Study</div></footer></>}

